#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.2"

# Which optional robotpy components should be installed?
# -> equivalent to `pip install robotpy[extra1, ...]
components = [
    # "all",
    "apriltag",
    "commands2",
    "cscore",
    # "romi",
    "sim",
    # "xrp",
]

# Other pip packages to install, such as vendor packages (each element
# is equivalent to a line in requirements.txt)
requires = [
    "phoenix6~=26.1",
    "robotpy-rev",
    "robotpy-navx",
    "robotpy-pathplannerlib"
]

## These poetry settings are only used for managing dependencies on dev machines. RobotPy does not evaluate them.

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "3.14.*"  # Pinned to the version that will be on the RIO / supported by robotpy
robotpy = "^2026.2.2"

[tool.poetry.group.dev.dependencies]
